name: Build and Deploy

# 当代码推送到主分支时触发这个 GitHub Action
on:
  push:
    branches:
      - master

jobs:
  # Build 阶段，用于构建 Maven 项目
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # 检出代码仓库

    - name: Set up JDK 11
      uses: actions/setup-java@v2  # 设置 Java 11 环境
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package  # 使用 Maven 构建项目

  # Deploy 阶段，用于将构建好的 JAR 文件复制到服务器
  deploy:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # 检出代码仓库

    - name: Set up JDK 11
      uses: actions/setup-java@v2  # 设置 Java 11 环境
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Deploy to Server
      run: scp -r target/*.jar liajing@${{secrets.REMOTE_IP}}:/Users/lijiang/Documents
